<!-- Begin Footer -->
<br /><br />
<div align="center">
<div align="center" style="border:dashed 1px #999; width:80%;">
	<p style="font-size:xx-small">Copyright &copy; 2012 by:
	Hartley Brody, Richardo Hopkins, Nicholas Wetzel, and Allen Tucker.<br />
	<i>Homeplate</i> was designed at <a href="http://www.bowdoin.edu/computer-science/" style="font-weight:normal;">Bowdoin College</a> for <a href="http://secondhelpingshhi.org/" target="_BLANK" style="font-weight:normal;">Second Helpings</a>, a
	non-profit food rescue organization in Beaufort County, South Carolina. 
	      <i>Homeplate</i> is free software and comes with absolutely no warranty.  You can redistribute and/or modify it under the terms of the
	     <a href="http://www.gnu.org/copyleft/gpl.html" style="font-weight:normal;"> GNU General Public License</a> as published by the <a href="http://www.fsf.org/"  style="font-weight:normal;"> Free Software Foundation</a>.
	</p>
</div>
</div>
<!-- End Footer -->