<!-- Begin Footer -->
<br /><br />
<div align="center">
<div align="center" style="border:dashed 1px #999; width:80%;">
	<p style="font-size:xx-small">Copyright &copy; 2012 by:
	Hartley Brody, Richardo Hopkins, Nicholas Wetzel, and <a href="http://myopensoftware.org/" style="font-weight:normal;">Allen Tucker</a>.<br />
	<i>Homeplate</i> was developed at <a href="http://www.bowdoin.edu/computer-science/" style="font-weight:normal;">Bowdoin College</a> for <a href="http://secondhelpingslc.org/" target="_BLANK" style="font-weight:normal;">Second Helpings</a>, a
	non-profit food rescue organization. 
	      <i>Homeplate</i> is free software and comes with absolutely no warranty.  You can redistribute and/or modify it under the terms of the
	     <a href="http://www.gnu.org/copyleft/gpl.html" style="font-weight:normal;"> GNU General Public License</a>.
	</p>
</div>
</div>
<!-- End Footer -->