<?PHP
	session_start();
	session_cache_expire(30);
?>
<!-- page generated by the BowdoinRMH software package -->
<html>
	<head>
		<title>
			Edit Master Schedule Shift
		</title>
		<link rel="stylesheet" href="styles.css" type="text/css" />
	</head>
	<body>
		<div id="container">
			<?PHP include('header.php');?>
			<div id="content">
				<?php
					if($_SESSION['access_level']<2) {
						die("<p>Only team captains can edit the master schedule.</p>");
					}
					$group=$_GET['group'];
					$area=$_GET['area'];
					$day=$_GET['day'];
					$area_names = array("HHI"=>"Hilton Head", "SUN"=>"Sun City", "BFT"=>"Beaufort");
					$day_names = array("Mon"=>"Monday","Tue"=>"Tuesday","Wed"=>"Wednesday",
									"Thu"=>"Thursday","Fri"=>"Friday","Sat"=>"Saturday","Sun"=>"Sunday");
					include_once('database/dbSchedules.php');
					include_once('domain/ScheduleEntry.php');
					include_once('database/dbVolunteers.php');
					include_once('domain/Volunteer.php');
					
				//	include_once('database/dbLog.php');
					if (!process_fill_vacancy($_POST,$group,$area,$day) &&  // try to fill a vacancy
					    !process_add_volunteer($_POST,$group,$area,$day)) // try to add a driver
					{
						if(process_unfill_shift($_POST,$group,$area,$day)){  // try to remove everyone
								
						}
					//	else if(process_add_slot($_POST,$group,$area,$day)) {	// try to add a new slot

					//	}
					//	else if(process_ignore_slot($_POST,$group,$area,$day)) {  //try to remove a slot

					//	}
						// we've tried to add or remove a person
						// so now display the outcome and present the options
						$the_entry = retrieve_dbSchedules($area, $day.":".$group);
						$drivers_scheduled=get_drivers_scheduled($area,$group,$day);
							    // $groupdisplay = $area . " Group ".$group;
								echo ("<table align=\"left\"><tr><td align=\"center\" colspan=\"2\"><b>
								Drivers scheduled for ".$area_names[$area].", ");
								if ($area=="BFT") echo $group." ".$day_names[$day]." of each month:";
								else echo $group." ".$day_names[$day]."s of the year:"; 
								echo ("</b></td></tr>");
								
								echo (display_filled_slots($drivers_scheduled)
									.display_vacant_slots(get_total_openings($area,$group,$day)));
								echo ("<tr><td valign=\"top\"><br>&nbsp;".get_total_openings($area,$group,$day)." openings</td><td>
									<form method=\"POST\" style=\"margin-bottom:0;\">
									<input type=\"hidden\" name=\"_submit_fill_vacancy\" value=\"1\"><br>
									<input type=\"submit\" value=\"Add Extra Driver\"
									name=\"submit\" >
									</form><br></td></tr>");	
									$returnpoint = "scheduleView.php?area=".$area;
								echo "<tr><td><a href=\"" .$returnpoint. "\">
										   Back to Driver Schedule</a>";
								echo ("</td></tr></table>");
						   }
				?>
				<br>
				</div>
				<?PHP include('footer.inc');?>		
		</div>
	</body>
</html>

<?php

function display_filled_slots($persons) {
		$s="";
		if(!$persons[0])
			array_shift($persons);
		for($i=0;$i<count($persons);++$i) {
			$person = retrieve_dbVolunteers($persons[$i]);
			if ($person)
			    $p = $person->get_first_name()." ".$person->get_last_name();
			else $p = $persons[$i];
			$s=$s."<tr><td valign=\"top\"><br>&nbsp;".$p."</td><td>
				<form method=\"POST\" style=\"margin-bottom:0;\">
				<input type=\"hidden\" name=\"_submit_filled_slot_".$i."\" value=\"1\"><br>
				<input type=\"submit\" value=\"Remove Driver\" name=\"submit\" >
			</form></td></tr>";
		}
		return $s;
}

function display_vacant_slots($vacancies) {
		$s="";
		for($i=0;$i<$vacancies;++$i) {
			$s=$s."<tr><td valign=\"top\"><br>&nbsp;<b>open</b></td><td>
				<form method=\"POST\" style=\"margin-bottom:0;\">
				<input type=\"hidden\" name=\"_submit_fill_vacancy\" value=\"1\"><br>
				<input type=\"submit\" value=\"Assign Driver\" name=\"submit\" ></form>
				</td></tr>";
		}
		return $s;
}

function process_add_volunteer($post,$group, $area, $day) {
		if(!array_key_exists('_submit_add_volunteer',$post))
			return false;
		if($post['all_vol']=="0" && $post['scheduled_vol']=="0")
			$error="<table align=\"center\"><tr><td width=\"400\">
				You must select a volunteer.</td></tr></table><br>";
		else if($post['all_vol']=="0") 
				$vol=$post['scheduled_vol'];
			else 
				$vol=$post['all_vol'];
		if($error) {
			echo $error;
			return true;
		}
		else {
			add_driver($area,$group,$day,$vol);
			return false;
		}
	}
	
function process_fill_vacancy($post,$group, $area, $day) {
		if(!array_key_exists('_submit_fill_vacancy',$post))
			return false;
		
		$groupdisplay = $area." week ".$group." ". $day;
		
		echo "<table align=\"left\"><tr><td align=\"center\"><b>
		Filling a vacancy for ".$groupdisplay."</b></td></tr>
		<tr><td><form method=\"POST\" style=\"margin-bottom:0;\">
			<select name=\"scheduled_vol\">
			<option value=\"0\" style=\"width: 371px;\">Select a driver with ".$group." ".$day." availability</option>"
			.get_available_volunteer_options($area,$day).
			"</select><br><br>
			<select name=\"all_vol\">
			<option value=\"0\" style=\"width: 371px;\">Select from all drivers in this area</option>"
			.get_all_volunteer_options($area).
			"</select><br><br>
			<input type=\"hidden\" name=\"_submit_add_volunteer\" value=\"1\">
			<input type=\"submit\" value=\"Add Volunteer\" name=\"submit\" >
			</form></td></tr>";
		echo "</table>";
		echo "<br><table align=\"left\"><tr><td align=\"left\" width=\"450\">
		<a href=\"scheduleEdit.php?group=".$group."&day=".$day."&area=".$area."\">Back to Route</a><br></td></tr></table>";
		return true;
}

function process_unfill_shift($post,$group, $area, $day) {
		$persons=get_drivers_scheduled($area, $group, $day);
		if(!$persons[0])
			array_shift($persons);
		for($i=0;$i<count($persons);++$i) {
			if(array_key_exists('_submit_filled_slot_'.$i, $post)) {
				remove_driver($area,$group,$day,$persons[$i]);
				return true;
			}
		}
		return false;
}
function get_available_volunteer_options($area,$day){
		$result=explode(';',getall_drivers_available($area,$day));
		$s="";
		for($i=0;$i<sizeof($result);++$i) {
			$row=$result[$i];
			$value=substr($row,0,strpos($row,":"));
			$label=substr($row,strpos($row,":")+1);
			$s=$s."<option value=\"".$value."\">".$label."</option>";
		}
		return $s;
}

function get_all_volunteer_options($area){
		$result=explode(';',getall_drivers_available($area,""));
		$s="";
		for($i=0;$i<sizeof($result);++$i) {
			$row=$result[$i];
			$value=substr($row,0,strpos($row,":"));
			$label=substr($row,strpos($row,":")+1);
			$s=$s."<option value=\"".$value."\">".$label."</option>";
		}
		return $s;
}
	
	

?>
